### ISSUE TITLE
Call to picocom

### ISSUE THREAD

**Issue by jdagilliland** [amperka/ino#19]
First of all, I just discovered ino, and am finding it essential to developing for the Uno on Linux, as the included GUI IDE is so clunky and Java-y, and the makefile included with the debian package 'arduino-core' does not seem to work well for the Uno. Thank you dearly for developing this magnificent jewel! The one imperfection I found (or rather, incongruency with my own habits) is that since the command 'ino serial' seems to call picocom only with default and hard-coded settings. This would not be a problem but that I like to use GNU Screen, and have long since become accustomed to ctrl-a being the escape sequence for that program. Thus, running 'ino serial' in a screen session cannot be interupted by ctrl-a because screen would intercept that as its own escape sequence; I wind up just stopping picocom with a 'killall picocom'. Perhaps a way to specify additional arguments for the picocom call in the 'ino serial' command could rectify this, as it seems that picocom's escape sequence is a command line configurable parameter; if only picocom had a config file I could change, I would, but alas it seems it has not.

Other than that, I can only say that 'ino' is just about the best piece of software I have found in a long time that did not come from a debian repository. IMHO it seems like it should be packaged with the 'testing' and 'unstable' of 'arduino-core'; if I ever get the time, I might offer to maintain the deb myself.

Sincerely, and perpetually in your debt,
Jason Daniel Augustine Gilliland
2012-01-26T1815EST

**Comment by nkrkv** [comment]
Thanks for your feedback! Glad to hear that ino is considered as something essential.

The ino serial part is somewhat rough and incomplete. There is a definitely room for improvements. One idea is to allow to pass arguments to a terminal software (picocom only at the moment) as is after `--` command line switch. That would be eventually done.

Unfortunately I'm very short of time to improve ino and this is done in quite rare work bursts. For this reason I can't make deb packaging yet. This was always like a piece of black magic to me. So if someone could help with packaging so that installation became as easy as `sudo apt-get install arduino-ino` after adding a PPA that would be fantastic. I suspect that many people comply about doing `sudo make install` for some not-well-known software.
