### ISSUE TITLE
ino build failed on Mac OS X

### ISSUE THREAD

**Issue by studer** [amperka/ino#22]
```
ino build --verbose
.build/arduino/wiring_pulse.d:1: *** missing separator.  Stop.
Make failed with code 2
```

The problem seems to be releated with the following command during the build process :

```
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc [...] /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c > .build/arduino/wiring_pulse.d
```

If I execute it manually, the file differs from the one generated by the automated build at the first line :

```
-n .build/arduino/wiring_pulse.d .build/arduino/
wiring_pulse.o:  \
```

The line beginning with `-n` seems to be the problem.

I am using Arduino 1.0 and ino 0.3.3 installed through pip 1.1 with python 2.7.1 on Mac OS X 10.7.3

**Comment by studer** [comment]
Actually, the problem is at line 23 inside the file `make/Makefile.deps.jinja` :

```
@echo -n "{{ target.path }} {{ target.path|dirname }}{{ slash }}" | cat - $@ > $@~ && mv $@~ $@
```

The content of `echo` is printed inside each file.

**Comment by fabiankr** [comment]
This needs to be fixed, but I'm too unfamiliar with the syntax of the jinja files to do it myself.  One should note, though, that this is the intention of the author. It just shouldn't cause compiler errors.

**Comment by zachrattner** [comment]
Is there any progress on this issue? I'm experiencing this problem on my Mac and I'm willing to help out if needed.

**Comment by johnhamelink** [comment]
I have this problem too!

**Comment by mvromer** [comment]
The issue seems to be the shell Make uses whenever it runs a target's list of commands.  By default Make will use /bin/sh, which on most systems is a symlink to something like Bash.  Bash's version of echo supports the -n option, which suppresses the newline character that echo would normally print out.  Essentially what the author is trying to do is prepend some paths to the contents of the first line in each *.d file that's generated under <project dir>/build/arduino/ during the build process.

However, the thing on OS X 10.7 is that /bin/sh appears to be not a link to some other shell but instead the actual Bourne shell (or at least something close to it).  In the Bourne shell, the echo command doesn't have a -n option and instead prints it as part of the output.  Consequently, it also prints a newline character, which is why it appears an extraneous garbage line in each *.d file.  Instead of using a -n command line option, the Bourne shell's echo command supported a \c character sequence, which basically was interpreted as "stopping printing output at this point".  All shells based on the Bourne shell (including Bash) still support this character sequence, so modifying the jinja file to use that instead of the -n option appears to fix this problem on my system.

[Here's](https://docs.google.com/open?id=0BxwlOmoWa5RCa1ltRjhLejhaNnc) a link to a patch I made that seems to fix this problem.  Simply applying it to the top-level distribution directory for ino and reinstalling ino should be all that's necessary to get this work.  If someone on Linux is using some other shell (like zsh) wants to try this patch on their system to confirm that it works as intended, then that'd be appreciated.

**Comment by nkrkv** [comment]
Perfect research, mvromer! Thank you.

Unfortunatelly `\c` doesn't work on linux unless `-e` option provided which is, again, will be printed as-is on MacOS. Fortunatelly we can use `printf` instead of `echo`. This solves the problem.

The patch is in repo already. Thanks again.
