### ISSUE TITLE
compile error: AdvButton example

### ISSUE THREAD

**Issue by ponty** [amperka/ino#7]
I get a compile error with AdvButton example.

This is the simplified AdvButton example:

``` C++
#include <AdvButton.h>

AdvButton but1 = AdvButton(0,OnKeyPressBut1,100,1000,btn_Digital);

void setup()
{
}

void OnKeyPressBut1(AdvButton* but)
{
}

void loop()
{
}
```

log:

```
$ ino build -m diecimila
make: Nothing to be done for `all'.
make: Nothing to be done for `all'.
src/buttondemo.cpp
.build/src/buttondemo.cpp:4: error: ‘OnKeyPressBut1’ was not declared in this scope
make: *** [.build/src/buttondemo.o] Error 1
```

**Comment by nkrkv** [comment]
You have to move OnKeyPressBut1 definition above it's first mention to conform the standard. Or you can forward-declare it right before the first usage:

``` cpp
#include <AdvButton.h>

void OnKeyPressBut1(AdvButton* but);
AdvButton but1 = AdvButton(0,OnKeyPressBut1,100,1000,btn_Digital);

// code below stays as is
```

**Comment by ponty** [comment]
I thought that project goal is to make ino compatible with arduino,
that's why I tried to help by testing working sketches with ino.
Some have build error, this is one example. 
However sketches can be always converted to "ino" compatible as you did it in the answer.
Directory structure is also not compatible. 

I compared ino and arscons with unit tests. Results:
- arscons (depends on scons): better compatibility 
- ino (depends on make): smaller code size

**Comment by nkrkv** [comment]
Ok, you're right. The goal _is_ to make ino compatible with Arduino Software and believe, your effort is valuable. However I have no very much time to immediately accept all such things.

What's related to this concrete example, I have no idea at the moment about how Arduino IDE works around the standard and allow forward-usage of functions. This is a topic for an investigation. But this issue is quite minor comparing to cross-platform support, configurable warnings support and some other stuff.

Thank you for participation!
