### ISSUE TITLE
If a function uses an enum, the CPP code has that above the enum def'n.

### ISSUE THREAD

**Issue by arkdae** [amperka/ino#74]
I have a .ino file with a function like this:

void twirly_bird(int column, int row, rotation rotate_dir)
{ ... }

rotation is an enum. If I define that enum above the function, or even in a separate file and #include it in, the code doesn't compile because a function declaration is created and placed at the very top of the generated .cpp file.

**Comment by drFerg** [comment]
I too have had a similar problem, when the prototypes are generated for all the functions (as per fix #16) they are placed at the top of the source file. This causes a problem as mentioned for enums as well as typedefs. Would it be possible to place the prototypes underneath the #includes or not recreate them if they previously exist(what arduino does since v1.0.2.

**Comment by cmtec** [comment]
+1

Following merge seems to solve this issue:
https://github.com/mash/ino/commit/57254908a2c94ceb60e6ee1ecf1ca1847d066d83

**Comment by larsenglund** [comment]
It doesn't solve it but my fix seems to do it.
